config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'
  devise_for :models
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy,:result,:change]
  root "resumes#index"
  get 'resumes/index'
  get 'resumes/create'
  get 'resumes/destroy'
  get 'resumes/result'
  get 'resumes/change'
  post 'resumes/change'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  validates :image_id,presence: true
  validates :pred_label,presence: true
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates :img_path,presence: true
  has_many :resumes
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :resumes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    resumes_index_path
  end
  def after_sign_out_path_for(resource_or_scope)
    resumes_index_path
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    build_resource({})
    set_minimum_password_length
    self.resource.company = Company.new
    yield resource if block_given?
    respond_with self.resource
  end

  def create
    super
    resource.update_attributes(role: :manager)
  end

  private

  def sign_up_params
    user_params = [:name, :email, :password, :password_confirmation, [company_attributes: [:name]]]
    params.require(resource_name).permit(user_params)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  def sign_up_params
    params.require(:user).permit(:email, :password, :name)
  end
  def index
    if(user_signed_in?)
      @resumes = Resume.where(:user_id => User.find(current_user.id))
    else
      @resumes = Resume.where(:user_id => nil)
    end
  end
  def new
    @resume = Resume.new
  end
  def create
    if(resume_params == nil)
      @resume = Resume.new()
      render "new"
    else
      if(resume_params[:true_label] == nil)
        ActionController::Parameters.permit_all_parameters = true
        file_name = (resume_params[:attachment]).original_filename
        cur_id = (user_signed_in?) ? User.find(current_user.id) : nil
        parampa = ActionController::Parameters.new(name:file_name,attachment: resume_params[:attachment],true_label: nil, pred_label: nil, user: cur_id)
        parampa= parampa.permit!
        @resume = Resume.new(parampa)
        if @resume.save
          redirect_to :controller => 'resumes', :action => 'result'
        else
          render "new"
        end
      else
        @res = Resume.order(:updated_at).last
        if(resume_params[:true_label] != "")
          Resume.update(@res[:id], :true_label => resume_params[:true_label])
        end
        redirect_to :controller => "resumes", :action => "index", notice: "The file #{@res[:name]} will be inspected and proceed, as soon as it possible"
        end
      end
    end
  def change
    @resume = Resume.new

  end
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The file #{@resume.name} has been deleted."
  end
  def result
    @resume = Resume.order(:updated_at).last
    labels = ['Cat','Dog','Elephant','Hamster']
    if(@resume[:pred_label] == nil )
      @pred_label = labels.sample
      Resume.update(@resume[:id], :pred_label => @pred_label,:true_label => @pred_label)
    else
      @pred_label = @resume[:pred_label]
    end


  end
  private
  def resume_params
    begin
      params.require(:resume).permit(:name, :attachment,:true_label)
    rescue ActionController::ParameterMissing
    end
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, address_attributes: [:country, :state, :city, :area, :postal_code]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
  def RandomLabel
    labels = ['Cat','Dog','Elephant','Hamster']
    return labels.sample
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Tutorialspoint</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class = "container" style = "padding-top:20px;">
  <%= yield %>
</div>
</body>

</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/resumes/change.html.erb
<h1>That's interesting... So what it is?</h1>
<div class = "well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label "True Label" %>
    <%= f.text_field :true_label %>
    <%= f.submit "Accept", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>

<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<h1>History</h1>
<% if !flash[:notice].blank? %>
  <div class = "alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<br />
<% if user_signed_in? %>
  <span>Здравствуйте, <%= current_user.email %></span>
  <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>
<%= link_to "New", new_resume_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
  <thead>.
  <tr>
    <th>Name</th>
    <th>Predicted Label</th>
    <th>True Label</th>
    <th>View</th>
    <th> </th>
  </tr>
  </thead>

  <tbody>
  <% @resumes.each do |resume| %>

    <tr>
      <td><%= resume.name %></td>
      <td><%= resume.true_label %></td>
      <td><%= resume.pred_label %></td>
      <td><%= link_to "Download", resume.attachment_url %></td>
      <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
    </tr>

  <% end %>
  </tbody>
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class = "alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <li>Sorry, but you can upload only files with jpg, png and jpeg types</li>
    </ul>
  </div>
<% end %>

<div class = "well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :file %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/resumes/result.html.erb
<h1>Is it <%= @pred_label%>?</h1>
<%= link_to "Yes", {:controller => :resumes, :action => :index}, class: "btn btn-primary" %>
<%= link_to "No", {:controller => :resumes, :action => :change}, class: "btn btn-primary" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>